# Generated by Django 5.1.4 on 2025-01-04 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 22, 27, 58, 837729, tzinfo=datetime.timezone.utc)),
        ),
    ]
